3f_3/src/java/jpa/entities/Users.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author ASUS
 */
@Entity
@Table(name = "users")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Users.findAll", query = "SELECT u FROM Users u")
    , @NamedQuery(name = "Users.findByRutUsers", query = "SELECT u FROM Users u WHERE u.rutUsers = :rutUsers")
        , @NamedQuery(name="Users.control", query="SELECT l FROM Users l WHERE l.username=:username AND l.password=:password")
    , @NamedQuery(name = "Users.findByNombreUsuario", query = "SELECT u FROM Users u WHERE u.nombreUsuario = :nombreUsuario")
    , @NamedQuery(name = "Users.findByApellidoUsuario", query = "SELECT u FROM Users u WHERE u.apellidoUsuario = :apellidoUsuario")
    , @NamedQuery(name = "Users.findByDireccionUsuario", query = "SELECT u FROM Users u WHERE u.direccionUsuario = :direccionUsuario")
    , @NamedQuery(name = "Users.findByTelefonoUsuario", query = "SELECT u FROM Users u WHERE u.telefonoUsuario = :telefonoUsuario")
    , @NamedQuery(name = "Users.findByCorreoUsuario", query = "SELECT u FROM Users u WHERE u.correoUsuario = :correoUsuario")
    , @NamedQuery(name = "Users.findByUsername", query = "SELECT u FROM Users u WHERE u.username = :username")
    , @NamedQuery(name = "Users.findByPassword", query = "SELECT u FROM Users u WHERE u.password = :password")})
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 20)
    @Column(name = "rut_users")
    private String rutUsers;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "nombre_usuario")
    private String nombreUsuario;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "apellido_usuario")
    private String apellidoUsuario;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "direccion_usuario")
    private String direccionUsuario;
    @Basic(optional = false)
    @NotNull
    @Column(name = "telefono_usuario")
    private int telefonoUsuario;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "correo_usuario")
    private String correoUsuario;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "username")
    private String username;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "password")
    private String password;
    @JoinColumn(name = "id_tipo", referencedColumnName = "id_tipo")
    @ManyToOne(optional = false)
    private TipoUser idTipo;

    public Users() {
    }

    public Users(String rutUsers) {
        this.rutUsers = rutUsers;
    }

    public Users(String rutUsers, String nombreUsuario, String apellidoUsuario, String direccionUsuario, int telefonoUsuario, String correoUsuario, String username, String password) {
        this.rutUsers = rutUsers;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.direccionUsuario = direccionUsuario;
        this.telefonoUsuario = telefonoUsuario;
        this.correoUsuario = correoUsuario;
        this.username = username;
        this.password = password;
    }

    public String getRutUsers() {
        return rutUsers;
    }

    public void setRutUsers(String rutUsers) {
        this.rutUsers = rutUsers;
    }

    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public String getApellidoUsuario() {
        return apellidoUsuario;
    }

    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }

    public String getDireccionUsuario() {
        return direccionUsuario;
    }

    public void setDireccionUsuario(String direccionUsuario) {
        this.direccionUsuario = direccionUsuario;
    }

    public int getTelefonoUsuario() {
        return telefonoUsuario;
    }

    public void setTelefonoUsuario(int telefonoUsuario) {
        this.telefonoUsuario = telefonoUsuario;
    }

    public String getCorreoUsuario() {
        return correoUsuario;
    }

    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public TipoUser getIdTipo() {
        return idTipo;
    }

    public void setIdTipo(TipoUser idTipo) {
        this.idTipo = idTipo;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (rutUsers != null ? rutUsers.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Users)) {
            return false;
        }
        Users other = (Users) object;
        if ((this.rutUsers == null && other.rutUsers != null) || (this.rutUsers != null && !this.rutUsers.equals(other.rutUsers))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Users[ rutUsers=" + rutUsers + " ]";
    }
    
}

3f_3/src/java/jsf/UsersController.java
package jsf;

import jpa.entities.Users;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.UsersFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("usersController")
@SessionScoped
public class UsersController implements Serializable {

    private Users current;
    private DataModel items = null;
    @EJB
    private jpa.session.UsersFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public UsersController() {
    }

    public Users getSelected() {
        if (current == null) {
            current = new Users();
            selectedItemIndex = -1;
        }
        return current;
    }

    private UsersFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Users) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Users();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("UsersCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Users) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("UsersUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Users) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("UsersDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Users getUsers(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Users.class)
    public static class UsersControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            UsersController controller = (UsersController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "usersController");
            return controller.getUsers(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Users) {
                Users o = (Users) object;
                return getStringKey(o.getRutUsers());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Users.class.getName());
            }
        }

    }

}

3f_3/web/users/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateUsersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateUsersLabel_rutUsers}" for="rutUsers" />
                    <h:inputText id="rutUsers" value="#{usersController.selected.rutUsers}" title="#{bundle.CreateUsersTitle_rutUsers}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_rutUsers}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_nombreUsuario}" for="nombreUsuario" />
                    <h:inputText id="nombreUsuario" value="#{usersController.selected.nombreUsuario}" title="#{bundle.CreateUsersTitle_nombreUsuario}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_nombreUsuario}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_apellidoUsuario}" for="apellidoUsuario" />
                    <h:inputText id="apellidoUsuario" value="#{usersController.selected.apellidoUsuario}" title="#{bundle.CreateUsersTitle_apellidoUsuario}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_apellidoUsuario}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_direccionUsuario}" for="direccionUsuario" />
                    <h:inputText id="direccionUsuario" value="#{usersController.selected.direccionUsuario}" title="#{bundle.CreateUsersTitle_direccionUsuario}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_direccionUsuario}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_telefonoUsuario}" for="telefonoUsuario" />
                    <h:inputText id="telefonoUsuario" value="#{usersController.selected.telefonoUsuario}" title="#{bundle.CreateUsersTitle_telefonoUsuario}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_telefonoUsuario}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_correoUsuario}" for="correoUsuario" />
                    <h:inputText id="correoUsuario" value="#{usersController.selected.correoUsuario}" title="#{bundle.CreateUsersTitle_correoUsuario}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_correoUsuario}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_username}" for="username" />
                    <h:inputText id="username" value="#{usersController.selected.username}" title="#{bundle.CreateUsersTitle_username}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_username}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_password}" for="password" />
                    <h:inputText id="password" value="#{usersController.selected.password}" title="#{bundle.CreateUsersTitle_password}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.CreateUsersLabel_idTipo}" for="idTipo" />
                    <h:selectOneMenu id="idTipo" value="#{usersController.selected.idTipo}" title="#{bundle.CreateUsersTitle_idTipo}" required="true" requiredMessage="#{bundle.CreateUsersRequiredMessage_idTipo}">
                        <f:selectItems value="#{tipoUserController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <center><h:commandLink action="#{usersController.create}" >
                                      <h:graphicImage library="images" name="Guardar.png" width="50" />

                    </h:commandLink> </center>   
     
           
                <center><h:link outcome="/login" >                   <h:graphicImage library="images" name="Regresar.png" width="100" />
                    </h:link></center>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

3f_3/web/users/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditUsersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditUsersLabel_rutUsers}" for="rutUsers" />
                    <h:inputText id="rutUsers" value="#{usersController.selected.rutUsers}" title="#{bundle.EditUsersTitle_rutUsers}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_rutUsers}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_nombreUsuario}" for="nombreUsuario" />
                    <h:inputText id="nombreUsuario" value="#{usersController.selected.nombreUsuario}" title="#{bundle.EditUsersTitle_nombreUsuario}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_nombreUsuario}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_apellidoUsuario}" for="apellidoUsuario" />
                    <h:inputText id="apellidoUsuario" value="#{usersController.selected.apellidoUsuario}" title="#{bundle.EditUsersTitle_apellidoUsuario}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_apellidoUsuario}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_direccionUsuario}" for="direccionUsuario" />
                    <h:inputText id="direccionUsuario" value="#{usersController.selected.direccionUsuario}" title="#{bundle.EditUsersTitle_direccionUsuario}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_direccionUsuario}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_telefonoUsuario}" for="telefonoUsuario" />
                    <h:inputText id="telefonoUsuario" value="#{usersController.selected.telefonoUsuario}" title="#{bundle.EditUsersTitle_telefonoUsuario}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_telefonoUsuario}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_correoUsuario}" for="correoUsuario" />
                    <h:inputText id="correoUsuario" value="#{usersController.selected.correoUsuario}" title="#{bundle.EditUsersTitle_correoUsuario}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_correoUsuario}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_username}" for="username" />
                    <h:inputText id="username" value="#{usersController.selected.username}" title="#{bundle.EditUsersTitle_username}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_username}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_password}" for="password" />
                    <h:inputText id="password" value="#{usersController.selected.password}" title="#{bundle.EditUsersTitle_password}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.EditUsersLabel_idTipo}" for="idTipo" />
                    <h:selectOneMenu id="idTipo" value="#{usersController.selected.idTipo}" title="#{bundle.EditUsersTitle_idTipo}" required="true" requiredMessage="#{bundle.EditUsersRequiredMessage_idTipo}">
                        <f:selectItems value="#{tipoUserController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{usersController.update}" value="#{bundle.EditUsersSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditUsersViewLink}"/>
                <br />
                <h:commandLink action="#{usersController.prepareList}" value="#{bundle.EditUsersShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditUsersIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

3f_3/web/users/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListUsersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListUsersEmpty}" rendered="#{usersController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{usersController.items.rowCount > 0}">
                    <h:outputText value="#{usersController.pagination.pageFirstItem + 1}..#{usersController.pagination.pageLastItem + 1}/#{usersController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{usersController.previous}" value="#{bundle.Previous} #{usersController.pagination.pageSize}" rendered="#{usersController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{usersController.next}" value="#{bundle.Next} #{usersController.pagination.pageSize}" rendered="#{usersController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{usersController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_rutUsers}"/>
                            </f:facet>
                            <h:outputText value="#{item.rutUsers}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_nombreUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombreUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_apellidoUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.apellidoUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_direccionUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccionUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_telefonoUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefonoUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_correoUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.correoUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_username}"/>
                            </f:facet>
                            <h:outputText value="#{item.username}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_password}"/>
                            </f:facet>
                            <h:outputText value="#{item.password}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsersTitle_idTipo}"/>
                            </f:facet>
                            <h:outputText value="#{item.idTipo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{usersController.prepareView}" value="#{bundle.ListUsersViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usersController.prepareEdit}" value="#{bundle.ListUsersEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usersController.destroy}" value="#{bundle.ListUsersDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{usersController.prepareCreate}" value="#{bundle.ListUsersCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListUsersIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>